---
# Converge playbook for Diffusion framework
# This prepares the test environment
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install base dependencies
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"
